In [99]:
#Task1
import numpy as np
# be sure to update the path below to reflect your own environment!!
# also be sure that the code is properly indented after you paste it!

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
#input a and b as arrays
np.intersect1d(a,b)
#compute the common elements between a and b


array([2, 4])

In [100]:
#Task2 
np.arange(1,16).reshape(3,5).T
#creat an array from 1 to 16
#the array should be 3*5,then transpose

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [101]:
#Task3
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
#input a and b
def Remove(x):#define a function that remove same items in a and b
    if x<7:
        c=np.delete(a,x,0)
        d=np.delete(b,x,0)
        #remove same items in a and b
        return c,d  
Remove(1)#use function to remove an items in a and it also same to b

(array([12,  7, 15,  3,  1,  8]), array([14,  3, 11, 19, 12,  5]))

In [102]:
#Task4
record=np.random.randint(1,1555,35)
#generate a series of integer numbers from 1 to 1555
#assume the total miles from NYC to FL is 1555
record=np.sort(record)
#sort the numbers such that it has order
record[7]=record[6]
record[14]=record[13]
record[21]=record[20]
record[28]=record[27]
#make sure that we have at least 4 days non-consecutive
record[34]=1555
#make sure the total mile is 1555
record

array([   2,   33,   78,  130,  167,  176,  192,  192,  270,  310,  429,
        440,  495,  516,  516,  725,  740,  840,  854,  889, 1083, 1083,
       1094, 1126, 1246, 1254, 1307, 1307, 1307, 1417, 1419, 1436, 1455,
       1503, 1555])

In [103]:
#Task 5
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


numpy.ndarray

In [104]:
#Question1 of task5 
np.max(nyc_water[:,2:3])
#get the maximum of consumption of water (max of 2nd column)

1512.0

In [105]:
#Question2 of task5 
print(nyc_water.shape)
#print the numbers of year which is the numbers of row

(39, 4)


In [106]:
#Question3 of task5 
print(np.mean(nyc_water[:,3:4]))
#get the mean value of capita daily water consumption (mean value of 3rd column)
print(np.std(nyc_water[:,3:4]))
#get the deviation of capita daily water consumption (deviation of 3rd column)

160.30769230769232
31.51894330370624


In [107]:
#Question4 of task5 
print('pop_diff:',np.diff(nyc_water[:,1:2].T,axis=1))
#use diff function to get the difference between adjacent two years of 1st column
#save as pop_diff variables

pop_diff: [[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
   11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
   64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
   16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
   77081.   61281.   49530.   44512.   21171.   85025. ]]
